image: nixos/nix:latest

stages:
  # - test
  - deploy

# Run tests:
#   stage: test
#   script:
#     - nix-shell tests -A run.all
#   only:
#     - master

Deploy manual:
  stage: deploy
  script:
    - mkdir -p ~/.config/nixpkgs
    - echo '{ manual.html.enable = true; }' > ~/.config/nixpkgs/home.nix
    - nix-shell . -A install
    - mkdir public
    - cp -r ~/.nix-profile/share/doc/home-manager/* public/
  artifacts:
    paths:
      - public
  only:
    - master

Deploy NUR:
  stage: deploy
  variables:
    HM_BRANCH: $CI_COMMIT_REF_NAME
    HM_COMMIT_SHA: $CI_COMMIT_SHA
  trigger:
    project: rycee/nur-expressions
    branch: home-manager
  only:
    - nur-pkgs
