[[sec-release-20.09]]
== Release 20.09 (unreleased)

This is the current unstable branch and the information in this
section is therefore not final.

[[sec-release-20.09-highlights]]
=== Highlights

This release has the following notable changes:

* Nothing has happened.

[[sec-release-20.09-state-version-changes]]
=== State Version Changes

The state version in this release includes the changes below. These
changes are only active if the `home.stateVersion` option is set to
"20.09" or later.

* The options <<opt-home.homeDirectory>> and <<opt-home.username>> no
longer have default values and must therefore be provided in the
user's configuration. Previously their values would default to the
values of the environment variables `HOME` and `USER`, respectively.
+
--
Further, the options <<opt-xdg.cacheHome>>, <<opt-xdg.configHome>>,
and <<opt-xdg.dataHome>> now unconditionally defaults to

- `"${config.home.homeDirectory}/.cache"`,
- `"${config.home.homeDirectory}/.config"`, and
- `"${config.home.homeDirectory}/.local/share"`.

Before they would honor the corresponding XDG environment variables.

This change in behavior was made to remove the reliance on the
non-deterministic function `builtins.getEnv`.
--
